name: Test GraalVM Native Image Agent
on:
  push:
    branches:
      - 'fix-522'

jobs:
  generate-native-image-metadata:
    name: Generate GraalVM Native Image Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Compile the project
        run:  |
          ./gradlew :openai-java-core:compileJava -x test

      - name: Run the Prism server
        run: |
          ./scripts/mock --daemon

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          cache: gradle

      - name: Run tests with the GraalVM native-image agent
        run:  |
          ./gradlew :openai-java-core:test -x compileJava -x compileTestJava -Pagent

      - name: Commit GraalVM metadata file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git status
          git add openai-java-core/src/main/resources/META-INF/native-image/reachability-metadata.json
          git commit -m "Add native-image reachability metadata [skip ci]" || echo "No changes to commit"
          git push
